### ISSUE TITLE
/pauserecording does not work

### ISSUE THREAD

**Issue by marvin1099** [REALDRAGNET/OBSCommand#1]
/pauserecording
does not work
/startrecording
works
is the " /pauserecording  " command wrong?
same btw with /resumerecording

**Comment by REALDRAGNET** [comment]
only /startrecording is a "built-in" command, for the other commands you have to use the /command feature:

/command=PauseRecording

/command=ResumeRecording

**Comment by marvin1099** [comment]
Thanks XD
