### ISSUE TITLE
Feature request support for HotKey and VirtualCam

### ISSUE THREAD

**Issue by globi84** [REALDRAGNET/OBSCommand#10]
Hi

your cli is very nice. Thanks for it.

is there a way to add support for the VirtualCam (Start/Stop/Status) Commands described [here](https://github.com/obsproject/obs-websocket/blob/4.9.1/docs/generated/protocol.md#virtual-cam-1) and the HotKeys Commannds from [here](https://github.com/obsproject/obs-websocket/blob/4.9.1/docs/generated/protocol.md#triggerhotkeybyname)

if this feature also available in your cli tool will this be great.

regards

**Comment by REALDRAGNET** [comment]
Hi

The /command and /sendjoson are universal commands where you can send any command you want that is supported by OBS-WEBSOCKET plugin. Several samples in the [discussion ](https://obsproject.com/forum/threads/command-line-tool-for-obs-websocket-plugin-windows.80243/)on OBS website.

**Comment by globi84** [comment]
Hi

thanks for your fast reply. 

This was to easy. Sorry that I disturb you. Have a nice day.

regards
