### ISSUE TITLE
Support Websockets v5 protocol

### ISSUE THREAD

**Issue by instinctualjealousy** [REALDRAGNET/OBSCommand#12]
Now that Websockets v5 is being included with OBS v28 prereleases, it might be a good time to support this so we don't need 4.9.1-compat.

**Comment by sikosis** [comment]
That would be great. I was shocked to find the plug-in was changed. I wish I didn’t update OBS but now that I have I’m stuck.

**Comment by instinctualjealousy** [comment]
There's now a 4.9.1-compat-Qt6 plugin you can use with OBS v28, but it's a stopgap- and all OBS websockets software should be updated to v5 because of this. I'm not even sure how you get to v4 and think the protocol is so bad it needs a compatibility-breaking rewrite for v5, but I say this as an uneducated outsider. Very few things support v5 so far and I hope the official adoption by OBS will help push adoption via connecting software.

**Comment by himpich** [comment]
https://github.com/BarRaider/obs-websocket-dotnet/releases

The Library from BarRaider has been updated, maybe that helps?

**Comment by REALDRAGNET** [comment]
Working on it, see my last post here: [https://obsproject.com/forum/threads/command-line-tool-for-obs-websocket-plugin-windows.80243/page-12](https://obsproject.com/forum/threads/command-line-tool-for-obs-websocket-plugin-windows.80243/page-12)

**Comment by REALDRAGNET** [comment]
OSCCommand updated to support V5 protocol
