### ISSUE TITLE
Error: ErrorCode: 403, Comment: The field value of 'sourceName' must not be empty

### ISSUE THREAD

**Issue by crackerbear** [REALDRAGNET/OBSCommand#13]
I upgraded OBS from v27 to v28 and with that, OBSCommand to 1.6.0. From your own post "built-in OBSCommand commands did not change syntax or wording", I'm using the same commands I did prior to upgrading however I'm now getting `Error: ErrorCode: 403, Comment: The field value of 'sourceName' must not be empty.` although everything still appears to be working despite that error.

The command I'm using is `OBSCommand.exe /profile=Twitch /hidesource="Monitor Left" /showsource="Monitor Right" /startrecording`

What should sourceName be or is it nonfunctional?

**Comment by REALDRAGNET** [comment]
Thank you for the feedback, yes /showsource does not work, fix in 1.6.1

**Comment by crackerbear** [comment]
Thanks for the quick fix!
