### ISSUE TITLE
Stupid Thing Holding Me Back

### ISSUE THREAD

**Issue by bennytheg** [REALDRAGNET/OBSCommand#2]
Issue type

Description
I'm using following bat script to TRY and get this working, I am using a stream deck to control my streaming PC using NDI from the other side of my house and I want the Stream Deck to stay plugged into my Gaming PC:

@echo OFF
cd /d D:\OBSCommand
OBSCommand.exe /server=//192.168.0.62:4444
OBSCommand.exe /scene=another
PAUSE

Except it doesn't change the scene, it just says "Ok" once.
And yes, I tried the IP with "//" and without to no avail.

Any ideas, I want to stream soon!

**Comment by REALDRAGNET** [comment]
/server must be issued in every line you are using OBSCommand.exe, it does not remember it (same with /password)

Try like that:
`OBSCommand.exe /server=92.168.0.62:4444 /scene=another`
