### ISSUE TITLE
Timeout not working?

### ISSUE THREAD

**Issue by loopy750** [REALDRAGNET/OBSCommand#3]
A minor issue, but looking at the update log, it says v1.2 should time out after about 4 seconds if server is not available, but using the latest (v1.5.3) it freezes indefinitely until the process is killed. Not a major issue, but with the way I'm using it, I need to use pskill.exe to kill the process.

**Comment by REALDRAGNET** [comment]
Indeed it was working in v1.2, but it looks like the move to the new generalized version of the OBSWebsocket.net framework broke it. The timeout functionality was not implemented correctly in the new framework. I have fixed that.

Thanks for reporting!
