### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by sobuj53** [REALDRAGNET/OBSCommand#4]
Hello,

When I try to use `/startrecording` command it shows me this,
![image](https://user-images.githubusercontent.com/25761237/117528795-dfb59600-aff5-11eb-9f70-786530415cc9.png)

But when I execute it with admin privilege, it executes but doesn't stat recording :(

What am I doing wrong?

I'm on windows 10 20H2

**Comment by sobuj53** [comment]
My bad I placed those files in `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps` which was causing this issue

**Comment by sobuj53** [comment]
Well it seems that even if I put it in any folder and add that folder in windows path variable then I'll also get this prompt

**Comment by REALDRAGNET** [comment]
Using windows path probably does not work because OBSCommand requires the working path set to the same path where OBSCommand.exe is, to be able to find its dependent files.
Also, make sure you have installed and configured the obs-websocket plugin.
Another possible cause might be the files are blocked. See https://winaero.com/how-to-unblock-files-downloaded-from-internet-in-windows-10/

**Comment by sobuj53** [comment]
Thank you for your reply. I'm using path this way 
![image](https://user-images.githubusercontent.com/25761237/117548511-3dc69580-b057-11eb-8e24-15862f93eebd.png)
where I've put all 4 files and also I've latest version obs-websocket plugin installed. Like I said, I can run OBSCommand  just fine if I open cmd window within the directory but accessing it with path not working.

**Comment by REALDRAGNET** [comment]
Windows will not find the dependent files even if you put them in the same directory, as long as the working path is not correct. You can't use OBSCommand like this (without adding extra workarounds). You need to be able to set the working directory to where you execute OBSCommand.exe.

Example. if it is in a batch file. You need to change the (working) directory to where OBSCommand.exe is:
```
c:\
cd C:\OBS_Cmd\
OBSCommand.exe /startrecording
```
If you can't set the working directory in whatever app you are using to start OBSCommand.exe, it's that app that has an issue, this is a must-have.

Maybe you can try to copy the dependent files to c:\Windows (and probably have to register them) to make it work, but not sure,

**Comment by sobuj53** [comment]
Thanks. I tied to register the dll using `regsvr32 "C:\Windows\Newtonsoft.Json.dll"` but couldn't as it was throwing error by saying it's not a valid dll !? anyway but yeah using full path works so thank you once again.

**Comment by sobuj53** [comment]
> Windows will not find the dependent files even if you put them in the same directory, as long as the working path is not correct. You can't use OBSCommand like this (without adding extra workarounds). You need to be able to set the working directory to where you execute OBSCommand.exe.
> 
> Example. if it is in a batch file. You need to change the (working) directory to where OBSCommand.exe is:
> 
> ```
> c:\
> cd C:\OBS_Cmd\
> OBSCommand.exe /startrecording
> ```
> 
> If you can't set the working directory in whatever app you are using to start OBSCommand.exe, it's that app that has an issue, this is a must-have.
> 
> Maybe you can try to copy the dependent files to c:\Windows (and probably have to register them) to make it work, but not sure,

unfortunately this is also giving me error :(
![image](https://user-images.githubusercontent.com/25761237/117559626-af7aff80-b0a8-11eb-8808-33d9b3bd3f53.png)

**Comment by sobuj53** [comment]
I'm so so sorry. actually the issue was not the command. My f***in windows defender had eaten up the file and and made it 0 bite. that's why I couldn't understand why it's not working. the file was there but it was dead. I'm sorry I should have noticed it earlier.
