### ISSUE TITLE
Set recording folder

### ISSUE THREAD

**Issue by sobuj53** [REALDRAGNET/OBSCommand#5]
Hello,

I'm trying to set recording folder location with OBSCommand, for this I've tried to use 

`OBSCommand.exe /command=SetRecordingFolder="D:\Programs" /startrecording`
this gives following output but starts recording (not in the mentioned location though)
_Error with command "SetRecordingFolder=D:\Programs": invalid request type_

and 

`OBSCommand.exe /SetRecordingFolder="D:\Programs" /startrecording`
This however doesn't throw any error and starts recording but not in the mentioned location either.

I've also tried `OBSCommand.exe /startrecording /saveToFilePath="D:\Programs\test.mkv" ` but no success.

Can you please tell me how can I set recording folder with OBSCommand?

**Comment by REALDRAGNET** [comment]
The syntax for the /command option is like this:
```
/command=mycommand,myparam1=myvalue1,myparam2=myvalue2...
                                  issues user command,parameter(s) (optional)
/command=mycommand,myparam1=myvalue1,myparam2=myvalue2,myparam3=mysubparam=mysubparamvalue
                                  issues user command,parameters and sub-parameters
```
If you replace the = with , and add the missing variable name "rec-folder", your line should look like this:
`OBSCommand.exe /command=SetRecordingFolder,rec-folder="D:\Programs" /startrecording`

"saveToFilePath" is not a command that is directly supported by OBSCommand, it only supports these commands:
/server=127.0.0.1:4444 /password=xxxx /delay=0.5 /setdelay=0.05 /profile=myprofile /scene=myscene /hidesource=myscene/mysource /showsource=myscene/mysource /togglesource=myscene/mysource /toggleaudio=myaudio /mute=myaudio /unmute=myaudio /setvolume=mysource,volume,delay /fadeopacity=mysource,myfiltername,startopacity,endopacity,[fadedelay],[fadestep] /slidesetting=mysource,myfiltername,startvalue,endvalue,[slidedelay],[slidestep] /slideasync=mysource,myfiltername,startvalue,endvalue,[slidedelay],[slidestep] /startstream /stopstream /startrecording /stoprecording /command=mycommand,myparam1=myvalue1... /sendjson=jsonstring

**For all other obs-websocket commands you need to use /command or /sendjson**

Using the "opposite" command makes it easier to get to the correct command values and syntax, e.g. to get the available json strings for "SetRecordingFolder" you can use "GetRecordingFolder":
`OBSCommand.exe /command=GetRecordingFolder`

The above will output something like this:
```
{
  "message-id": "5IGqCCN5lsl4NELN",
  "rec-folder": "D:\Programs",
  "status": "ok"
}
Ok
```
as you can see the json variable name is "rec-folder".

You can also see this in the protocol description of obs-websocket: https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md

**Comment by sobuj53** [comment]
Thank you very much for your in depth explanation. You are very kind :)
