### ISSUE TITLE
Error: delay is not numeric - Regional/Language windows settings - "," is used instead of "."

### ISSUE THREAD

**Issue by moaxoam** [REALDRAGNET/OBSCommand#6]
Hi, 

Using Swedish Windows (10) settings the /delay=5.5 like below doesn't work, it bypasses it. Exchanging the "." to "," then it becomes 55 seconds.
When using "Preferred Language" "English (United States)" instead, it works.

```OBSCommand.exe /server=127.0.0.1:4444 /password="" /scene="Scene 3" /delay=3 /scene="Scene 2" /delay=5.5 /scene="Scene 3" Error: delay is not numeric```

**Comment by REALDRAGNET** [comment]
Hi,

That should have been fixed long ago, I have addressed decimal separator issues in 2019.

I did a quick test, by changing Windows's decimal separator settings (that should be the same as changing to another display language) from "." to ",", and I can not reproduce this testing with the /delay option.

Before I'm going to download Swedish language, are you sure you are using a recent or latest version of OBSCommand?
