### ISSUE TITLE
toggle filter

### ISSUE THREAD

**Issue by AmirGhorbani2001** [REALDRAGNET/OBSCommand#7]
hi
 i cant find any command for toggle the filters
 is that not exist on obs command? 
 <3 for any answer :D

**Comment by REALDRAGNET** [comment]
Hi, this is only for bugs and issues with the program. I do not answer questions like this here.

Questions go here (where this question already has been answered): https://obsproject.com/forum/threads/command-line-tool-for-obs-websocket-plugin-windows.80243/
